language: rust
dist: trusty
sudo: required

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache:
  cargo: true
  directories:
    - $HOME/php-7.1.10

install:
 - sudo sh ./.travis/install-php.sh php-7.1.10

before_script:
 - export PHP_LIB_DIR=~/php-7.1.10/libs
 - export PHP_INCLUDE_DIR=~/php-7.1.10
 - export LD_LIBRARY_PATH=~/php-7.1.10/libs
