language: rust
dist: trusty
sudo: required

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache:
  cargo: true
  directories:
    - $HOME/php-src

install:
 - sudo sh ./.travis/install-php.sh

before_script:
 - export PHP_LIB_DIR=~/php-src/libs
 - export PHP_INCLUDE_DIR=~/php-src
 - export LD_LIBRARY_PATH=~/php-src/libs
