[package]
name = "php-rpm"
version = "0.1.0"
authors = ["Herman J. Radtke III <herman@hermanradtke.com>"]

[dependencies]
log = "0.3.8"
hyper = "0.11"
futures = "0.1"

[build-dependencies]
bindgen = "0.29"
