[package]
name = "php-sys-ng"
version = "8.2.9"
authors = ["Herman J. Radtke III <herman@hermanradtke.com>", "Heinz Gies <heinz@licenser.net>"]
links = "php7"
build = "build.rs"

[build-dependencies]
bindgen = "0.66"
cc = "1.0"
num_cpus="1.0"
